### ISSUE TITLE
Module Can Make Undo Impossible

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/align-to-origin#3]
Using the module with `alignOnSave = true` can make undo impossible. When a user wants to save on `commandStack.changed` he won't be able to undo in some cases.

You can reproduce the issue using this CodeSandbox: https://codesandbox.io/s/undo-bug-o8v0q

1. Delete the start event
2. Click _Undo_
3. Nothing happens 😢

**Comment by nikku** [comment]
Closing this issue for the reason described in https://github.com/bpmn-io/align-to-origin/issues/2#issuecomment-787066522.

To sum it up, this module is not compatible with `commandStack.changed` intercepting autoSave behaviors.
